modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"
[[mods]]
modId = "sculkyextras"
version = "${file.jarVersion}"
displayName = "SculkyExtras"
authors = "KaboomRoads"
description = '''
Extra features for Sculky Bits.
'''
[[dependencies.sculkyextras]] #optional
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.sculkyextras]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.sculkyextras]]
modId = "sculkybits"
mandatory = true
versionRange = "[1.0.1,)"
ordering = "NONE"
side = "BOTH"
